#!/usr/bin/env ansible-playbook

- name: show return value of command module
  hosts: web

  tasks:
    - name: capture output of id command
      command: id -un
      register: login
    - debug: var=login
